---
title: "3-5 Follow Along"
author: "Grace MacKay"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("here")
#install.packages("ggplot2", dependencies = TRUE)
library(tidyverse)
library(gapminder)
library(here)
library(readxl)
```

```{r from computer}
(gap_asia_2007 <- gapminder %>% filter(year == 2007, continent == "Asia"))

write_csv(gap_asia_2007, here::here("data", "s008_data", "exported_file.csv"))

read_csv(here::here("data", "s008_data", "exported_file.csv"))

imported_data <- read_csv(here::here("data", "s008_data", "exported_file.csv"))

?read_csv
```

```{r reading from url}
url <- "http://gattonweb.uky.edu/sheather/book/docs/datasets/magazines.csv"

read_csv(url)

##OR

read_csv("http://gattonweb.uky.edu/sheather/book/docs/datasets/magazines.csv")
```

```{r from excel}
#library(readxl)
## dir.create(here::here("data", "s008_data"), recursive = TRUE) #this will create the folders in the file path into the directory. If the recursive = FALSE it will only create the last folder

xls_url <- "http://gattonweb.uky.edu/sheather/book/docs/datasets/GreatestGivers.xls"
download.file(xls_url, here::here("data", "s008_data", "some_file.xls"), mode = "wb") #windows especially needs the mode = "wb" part at the end or there will be problems with corrupted files
# try to give the files good names so that you can remember them when you come back to them later

file_name <- basename(xls_url)
download.file(xls_url, here::here("data", "s008_data", file_name), mode = "wb")

read_excel(here::here("data", "s008_data", file_name))
```

```{r reading SPSS}
(clevel <- haven::read_spss(here::here("data", "s008_data", "clevel.sav")))
```

```{r converting factors}
clevel_cleaned <-
  clevel %>% 
  mutate(language = as_factor(language), #this is converting from double+label to factor
         gender = as_factor(gender), ##this is converting from double+label to factor
         isClevel = factor(isClevel, # converting the isClevel into a factor
                           levels = c(0, 1), #indicating what the labels are
                           labels = c("No", "Yes")) #giving a new factor name-label to the levels
  ) %>% 
  print()

write_csv(clevel_cleaned, here::here("data", "s008_data", "clevel_cleaned.csv")) #r can also create something into an SPSS file
```

```{r making a plot}
clevel_plot <-
  clevel_cleaned %>% 
  mutate(isClevel = recode(isClevel, 
                           No = "Below C-level", 
                           Yes = "C-level"),
         gender = recode(gender,
                         Female = "Women",
                         Male = "Men")) %>% 
  ggplot(aes(paste(isClevel, gender, sep = "\n"), Extraversion, color = gender)) +
  geom_boxplot() +
  geom_jitter(height = .2) +
  scale_color_manual(values = c("#1b9e77", "#7570b3")) +
  ggtitle("Extraversion Stan Scores") +
  scale_y_continuous(breaks = 1:9) +
  ggthemes::theme_fivethirtyeight() #%>% 
  print(clevel_plot)
```

```{r save graph}
#install.packages("svglite") error if not installed
library(svglite)
dir.create(here::here("output", "figures"), recursive = TRUE) #if you don't have recursive = TRUE is missing it will only create the last folder but if you include it then it will create all of the folders starting from the initial directory point
ggsave(here::here("output", "figures", "clevel_extraversion.svg"), clevel_plot)
```

```{r saving other versions}
ggsave(here::here("output", "figures", "clevel_extraversion.eps"), clevel_plot) ## given an error: Error in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) : family 'sans' not included in postscript() device
ggsave(here::here("output", "figures", "clevel_extraversion.pdf"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.tiff"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.png"), clevel_plot)
```













